# Generated by Django 2.2.2 on 2019-07-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190610_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitems',
            name='owner_district',
            field=models.CharField(default='empty', max_length=40),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='owner_province',
            field=models.CharField(default='empty', max_length=40),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='owner_sector',
            field=models.CharField(default='empty', max_length=40),
        ),
    ]
