# Generated by Django 2.2.2 on 2019-07-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190716_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostitems',
            old_name='owner_province',
            new_name='owner_cell',
        ),
        migrations.AddField(
            model_name='lostitems',
            name='owner_umudugudu',
            field=models.CharField(default='empty', max_length=40),
        ),
    ]
