# Generated by Django 2.2.2 on 2019-07-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190716_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitems',
            name='found_cell',
            field=models.CharField(default='empty', max_length=40),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='found_district',
            field=models.CharField(default='empty', max_length=40),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='found_sector',
            field=models.CharField(default='empty', max_length=40),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='found_umudugudu',
            field=models.CharField(default='empty', max_length=40),
        ),
    ]
