# Generated by Django 2.2.2 on 2019-07-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_foundbutnotassigned_found_doc_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundbutnotassigned',
            name='owner_id',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AddField(
            model_name='foundbutnotassigned',
            name='owner_name',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AddField(
            model_name='foundbutnotassigned',
            name='owner_phone',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AddField(
            model_name='foundbutnotassigned',
            name='status',
            field=models.CharField(default='empty', max_length=40),
        ),
    ]
