# Generated by Django 2.2.2 on 2019-07-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190723_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitems',
            name='owner_id',
            field=models.CharField(default='empty', max_length=40),
        ),
        migrations.AlterField(
            model_name='foundbutnotassigned',
            name='status',
            field=models.CharField(default='Not Found', max_length=40),
        ),
    ]
